name: updater
description: A package to check for the custom in-app updates for Flutter.
version: 0.1.5
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.3
  http: ^0.13.5
  open_filex: ^4.3.2
  package_info_plus: ^3.0.3
  path_provider: ^2.0.14

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin
      ios:
        pluginClass: UpdaterPlugin
  