name: updater
description: A package to check for the custom in-app updates for Flutter.
version: 0.2.5
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  platform: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin
      # ios:
      #   pluginClass: UpdaterPlugin
  
