name: updater
description: A package to check for the custom in-app updates for Flutter.
version: 0.2.4
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.4
  http: ^1.1.2
  open_filex: ^4.3.4
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  platform: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.6

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin
      ios:
        pluginClass: UpdaterPlugin
  
